environment:
  nodejs_version: "8"
  MOCHA_TIMEOUT: "60000"
  NO_BREAKPOINTS: "1"

install:
  - cmd: appveyor-retry powershell Install-Product node $env:nodejs_version
  - cmd: appveyor-retry yarn
  - cmd: appveyor-retry yarn bootstrap:remote

build: off

test_script:
  - yarn build
  - cmd: yarn test:world -- --timeout $env:MOCHA_TIMEOUT
  - cmd: yarn test:unit -- --timeout $env:MOCHA_TIMEOUT
  - cmd: yarn test:integration -- --timeout $env:MOCHA_TIMEOUT
  - cmd: yarn test:scenarios -- --timeout $env:MOCHA_TIMEOUT
  - yarn dist:all

on_failure:
  - node --version
  - npm --version
  - yarn --version
