sudo: false
language: node_js
matrix:
    fast_finish: true
    allow_failures:
        - node_js: 4
node_js:
    - 0.10
    - 0.12
    - 4
env:
    global:
        - NODE_ENV=test
services:
    - couchdb
cache:
    directories:
        - node_modules
addons:
    apt:
        packages:
            - net-tools

before_install:
    - cd
    - npm install forever coffee-script mocha -g
    - git clone git://github.com/cozy/cozy-data-system.git
    - cd cozy-data-system
    - npm install #data-system
    - pwd
    - NAME=data-system TOKEN=token forever start -o forever-ds.log -e forever-ds-err.log build/server.js
    - sleep 5
    - pwd
    - cd
    - git clone git://github.com/cozy/cozy-proxy.git
    - cd cozy-proxy
    - npm install
    - pwd
    - NAME=proxy TOKEN=token forever start -o forever-proxy.log -e forever-proxy-err.log build/server.js
    - sleep 5
    - 'curl -X POST -H "Content-Type: application/json" -d "{ \"email\": \"cozytest@cozycloud.cc\", \"password\": \"cozytest\", \"timezone\":\"Europe/Paris\"}" http://127.0.0.1:9104/register'
    - cd
    - git clone git://github.com/cozy/cozy-files.git
    - cd cozy-files
    - npm install
    - pwd
    - cd ~/cozy-data-system
    - coffee commands.coffee test-install files ../cozy-files/package.json
    - pwd
    - cd ~/cozy-files
    - NAME=files TOKEN=apptoken forever start -o forever-files.log -e forever-files-err.log build/server.js
    - sleep 3
    - cd /home/travis/build/cozy-labs/cozy-desktop
    - pwd

script:
    - bin/ci

after_failure:
    - pwd
    - ps aux | grep server.js
    - netstat -lntp
    - cat ~/cozy-data-system/forever-ds.log
    - cat ~/cozy-data-system/forever-ds-err.log
    - cat ~/cozy-proxy/forever-proxy.log
    - cat ~/cozy-proxy/forever-proxy-err.log
    - cat ~/cozy-files/forever-files.log
    - cat ~/cozy-files/forever-files-err.log
    - curl -v http://localhost:9101/
    - curl -v http://localhost:9104/
    - curl -v http://localhost:9121/
    - ping -n -w 2 -c 1 localhost
    - ping -n -w 2 -c 5 -v localhost
