language: node_js
node_js:
    - "0.10"
env:
    global:
        - NODE_ENV=test
services:
    - couchdb
env:
    global:
        - NODE_ENV=test
        - TEST_ENV=travis
before_install:
    - cd
    - npm install forever coffee-script -g
    - git clone git://github.com/cozy/cozy-data-system.git
    - cd cozy-data-system
    - npm install #data-system
    - pwd
    - NAME=data-system TOKEN=token forever start -o forever-ds.log build/server.js
    - sleep 5
    - 'curl -X PUT -H "Content-Type: application/json" -d "{ \"email\": \"cozytest@cozycloud.cc\", \"owner\": true, \"password\": \"$2a$10$VwA77zUtGj9GoMROFSyyT.2rGrFtqUrF77DGg0Ev3ms6wRNM9HX6q\", \"salt\": \"q24unp9k8qe0cnmiqu3pnhti\", \"public_name\": \"\", \"timezone\": \"GMT\", \"activated\": true, \"docType\": \"User\", \"slaveKey\": \"m87KWEbhpcKm0LDSVymzucyiTAw6OmUBOusdzqalBhrdEzQrVvOMyJ/i5szicln8\" }" http://127.0.0.1:5984/cozy/c50145ae3b1e732dcdb990271400108c'
    - pwd
    - cd
    - git clone git://github.com/cozy/cozy-proxy.git
    - cd cozy-proxy
    - npm install
    - pwd
    - NAME=proxy TOKEN=token forever start -o forever-proxy.log build/server.js
    - sleep 3
    - cd
    - git clone git://github.com/cozy/cozy-files.git
    - cd cozy-files
    - npm install
    - pwd
    - cd ~/cozy-data-system
    - coffee commands.coffee test-install files ../cozy-files/package.json
    - pwd
    - cd ~/cozy-files
    - NAME=files TOKEN=apptoken forever start -o forever-files.log build/server.js
    - sleep 3

script:
    - cd /home/travis/build/Kloadut/cozy-desktop
    - npm install
    - node_modules/.bin/gulp test

after_failure:
    - ps aux | grep server.js
    - sudo netstat -plunt
    - cat ~/cozy-data-system/forever-ds.log
    - cat ~/cozy-proxy/forever-proxy.log
    - cat ~/cozy-files/forever-files.log
    - curl http://localhost:9101/
    - curl http://localhost:9104/
    - curl http://localhost:9121/
