---
dist: trusty
sudo: false
language: node_js
matrix:
    fast_finish: true
    include:
        - os: linux
          node_js: 4
          env: CXX=g++-4.8
        - os: linux
          node_js: 6
          env: CXX=g++-4.8
        - os: linux
          node_js: 7
          env: CXX=g++-4.8
        - os: osx
          node_js: 4
    allow_failures:
        - os: osx
          node_js: 4
env:
    global:
        - COZY_DESKTOP_DIR=tmp
        - NODE_ENV=test
        - NPM_CONFIG_PROGRESS=false
services:
    - docker
cache:
    directories:
        - node_modules
        - /Library/Caches/Homebrew
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.8
            - g++-4.8

# install cozy stack for integration test
before_install:
    # CouchDB 2
    - docker run -d -p 5984:5984 --name couch klaemo/couchdb:2.0.0

    # Go 1.7
    - gimme 1.7

    # Cozy stack v3
    - go get -u github.com/cozy/cozy-stack
    - curl -X PUT http://127.0.0.1:5984/{_users,_replicator,_global_changes}
    - $GOPATH/bin/cozy-stack serve --assets=$GOPATH/src/github.com/cozy/cozy-stack/assets &
    - sleep 1
    - $GOPATH/bin/cozy-stack instances add --dev "localhost:8080"

    # Cozy desktop tmp dir
    - cd $HOME/build/cozy-labs/cozy-desktop
    - pwd
    - mkdir /tmp/cozy-desktop
    - ln -s /tmp/cozy-desktop tmp

script:
    - npm run build
    - npm run lint
    - npm run test-unit-coverage
    - cd gui
    - yarn
    - npm run lint
    - npm run build
    - cd ..

after_success:
    - bash <(curl -s https://codecov.io/bash)

after_failure:
    - pwd
    - $CXX --version
    - ps aux | grep server.js
    - netstat -lntp
    - cat ~/cozy-data-system/forever-ds.log
    - cat ~/cozy-data-system/forever-ds-err.log
    - cat ~/cozy-proxy/forever-proxy.log
    - cat ~/cozy-proxy/forever-proxy-err.log
    - cat ~/cozy-files/forever-files.log
    - cat ~/cozy-files/forever-files-err.log
    - curl -v http://localhost:9101/
    - curl -v http://localhost:9104/
    - curl -v http://localhost:9121/
