environment:
  nodejs_version: "6"
  COZY_URL:
    secure: uO9y1OhE9RrwDoYV5ewQPWITVjiTLzLO+dxhyOxpzoU=
  COZY_PASSPHRASE:
    secure: YQQimbK6g91kgTePrPHKl92Pu3O1Hjqsm+HjUUTmZEM=

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn
  - yarn bootstrap:remote

build: off

test_script:
  - yarn test-unit

on_failure:
  - node --version
  - npm --version
  - yarn --version
