version: '2.1'
services:
  cozy:
    container_name: cozy-desktop-stack
    build: ./dev/cozy-stack
    ports:
      - "8080:8080"
      - "8025:8025"
      - "5984:5984"
    volumes:
      - .:/cozy-desktop
      - ./tmp/couchdb:/usr/local/couchdb/data
      - ./tmp/cozy-storage:/data/cozy-storage
